import Head from "next/head";
import { Logo } from "../components/Logo/logo";
import React from "react";
import { FormGroup } from "../components/Forms/FormGroup/Formgroup";
import { DCol, Table } from "../components/Table/Table";
import { IButton } from "../components/Buttons/button";
export default function About() {
  const testColumns: DCol[] = [
    { header: "Test 1", valueField: "id" },
    { header: "Test 2", valueField: "u" },
    { header: "Test 3", valueField: "v" },
    { header: "Test 4", valueField: "d" },
    { header: "Test 5", valueField: "id" },
    { header: "Test 6", valueField: "u" },
    {
      header: "Test 7",
      valueField: "v",
      type: "icon",
      icon: <IButton icon={<i>+</i>} text={"Add to Slip"} />,
    },
  ];
  const data = [
    { id: 1, v: "Test", u: "Test of his mettle", d: "Jan - 1" },
    { id: 2, v: "Test", u: "English premier league", d: "Jan - 1" },
    { id: 3, v: "Test", u: "Test of his mettle", d: "Jan - 1" },
    { id: 4, v: "Test", u: "French lIGUE 1", d: "Jan - 1" },
  ];
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About Page</h1>
        <Logo />
        <FormGroup
          type={"checkbox"}
          placeholder={"Enter your text"}
          label={"Sample"}
        />
        <Table columns={testColumns} data={data} />
      </main>
    </>
  );
}
