import Head from "next/head";
import { Logo } from "../components/Logo/logo";
import { Input } from "../components/Forms/Input/Input";
import React from "react";
import { FormGroup } from "../components/Forms/FormGroup/Formgroup";
export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About Page</h1>
        <Logo />
        <FormGroup
          type={"checkbox"}
          placeholder={"Enter your text"}
          label={"Sample"}
        />
        <Input type={"select"} options={["hi", "there"]} />
      </main>
    </>
  );
}
